### ISSUE TITLE
iterating over atomics, lights and cameras in a rw::Clump

### ISSUE THREAD

**Issue by quiret** [aap/librw#10]
https://github.com/aap/librw/blob/master/src/rwobjects.h#L665

While a rw::Clump object can store atomics, cameras and lights, there is currently no easy way to iterate over them. In original RW there were functions called RwClumpForAllAtomics, RwClumpForAllLights, RwClumpForAllCameras with a custom callback function. Can you please implement something like that? I would greatly appreciate it if you use modern C++ lambdas instead!

**Comment by aap** [comment]
Callbacks fucking suck, FORLIST is awesome!
