### ISSUE TITLE
What's missing from the original RenderWare?

### ISSUE THREAD

**Issue by luizfernandonb** [aap/librw#119]
In the README it says that this library is supposed to be a re-implementation of the original RenderWare, how close is this library currently to the original implementation?

**Comment by aap** [comment]
Hm, hard to say exactly. RW has many plugins that i never bothered with. I've mostly focused on the core and the world, matfx, and skin plugins. from world there still is no bsp support at all and no real support for morph animation either. other than that i do want good ps2 support and have actually been working towards it the last few weeks.

**Comment by luizfernandonb** [comment]
> Hm, hard to say exactly. RW has many plugins that i never bothered with. I've mostly focused on the core and the world, matfx, and skin plugins. from world there still is no bsp support at all and no real support for morph animation either. other than that i do want good ps2 support and have actually been working towards it the last few weeks.

Got it, so that's about 60% close to the original implementation? considering that we can run re3 and other renderware games without crashes (from what I researched and saw)

these days I compiled re3 and I can play normally without crashes, I just haven't tested reVC yet

**Comment by luizfernandonb** [comment]
For example, do I believe it's possible to inject this rewritten RenderWare into GTA SA and get the game to run normally?

**Comment by aap** [comment]
librw is not binary compatible with RW. so no, that won't work. It is to a high degree source compatible if you write the necessary wrappers (as I've done for re3/reVC). librw was indeed mostly written with gta in mind, but it's not really specific to it. although the things that it's missing tend to be things that gta doesn't use.

**Comment by luizfernandonb** [comment]
Thanks!
