### ISSUE TITLE
A question about the Android GTA rw engine

### ISSUE THREAD

**Issue by xiaogui824** [aap/librw#123]
@aap What aspects are related to the size of the dff model file loaded by the gta game?  Why doesn't the game support the larger MB model.

In the PC version of the GTA game, I tested GTAVC, and I found that the game cannot render vehicle models larger than 15M, and it crashes when the game is about to render this model.  Even it doesn't support dff models for larger characters, maps.  But in GTASA, it supports relatively large models (I tried 30M to run).
----------------------------------------

But in the Android version of VC, models exceeding 1m will inevitably collapse.  When it's time to render this large model, it keeps crashing in game.  In Android sa I'm not sure how many MB models it supports up to, but it also has an upper limit.  What causes this?  Is it the cause of the engine?  Or something else?  I want to solve this problem in android gta, maybe you have more experience to answer me.

**Comment by aap** [comment]
I don't know. Probably not easy to find out and debugging on android is hard. also i don't do gta anymore, so i can't help.
