### ISSUE TITLE
What is gonna happend with re3/revc?

### ISSUE THREAD

**Issue by ppastene** [aap/librw#124]
Yes, I know this is not the place to ask about it but I couldn't find another way to contact directly to the devs.

After the lawsuit, what is gonna happend with librw and most importnat, with re3/revc project? Are you gonna resume the development, start over, or is settled to not decompile the games anymore?  Because after reading @aap  bio saying "Ex-GTA hacker" I believe you decided the 3rd option, which is a big shame considering GTA VC is one of my most beloved games with a lot of potential on modding, and being a big enthusiast of open source, modding and gaming preservation is a big loss to see a project like this being dumped directly to the trash, and I know, there's nothing to do against the publisher but after what happended with FiveM maybe you could do another shot

If I have the knowledge of C++, reverse enginnering and debugging I surely have keep working on this, sadly I'm just a low tier PHP programmer which recently I'm learning Go

Best of luck to all the devs involved on this, and take care

**Comment by aap** [comment]
gta is over. librw is alive but of course doesn't see as much activity as it used to because i mostly used it for gta purposes.

**Comment by ppastene** [comment]
> gta is over. librw is alive but of course doesn't see as much activity as it used to because i mostly used it for gta purposes.

This makes me so sad, I was looking everyday if the Discord server went open again but seeing the current actions of the publisher and the developers I can say this is a bad day to be a fan of GTA (and I'm not even interested on VI).

At least let me thank you and all the devs for your time developing re3/revc, one of my dreams was to see GTA VC reverse engineered and open source to unlock its real potential and you acomplish it after many years of research. I could wish to have the knowledge to continue this but maybe I'll never learn the stuff all of you applied, so I'll be waiting if you wanna hit the road again

Godspeed, and take care
