### ISSUE TITLE
Can I build this without re3?

### ISSUE THREAD

**Issue by shoddydev** [aap/librw#127]
Hello I'm working on a PlayStation Classic gta3 port and I got it to run with re3, but I'm curious if I can build librw by itself without re3 and run GTA3 or do I need re3 also?

**Comment by PerikiyoXD** [comment]
Yes, you can build librw independantly as a library.
re3 uses librw as a compatible Renderware replacement library.
To actually use librw on GTA3 executable, you would need to create an "ASI" mod which patches every Renderware function found in GTA3 binary and properly adjust the existing code.

**Comment by aap** [comment]
Not quite sure what your plan is. gta3 obviously doesn't use librw and you cannot easily make it compatible either. re3 is dead, but you can use librw for other RW-related things.

**Comment by shoddydev** [comment]
> Yes, you can build librw independantly as a library. re3 uses librw as a compatible Renderware replacement library. To actually use librw on GTA3 executable, you would need to create an "ASI" mod that patches every Renderware function found in GTA3 binary and properly adjust the existing binary code.

I see. I think that's beyond what I'm capable of at the moment. I was wondering if I can just build it, then have it launch gta3 without me having to code or create anything after. I can follow instructions on how to compile and build things, but I don't know anyting about coding yet. But maybe in the future.

> Not quite sure what your plan is. gta3 obviously doesn't use librw and you cannot easily make it compatible either. re3 is dead, but you can use librw for other RW-related things.

the goal is to provide users the ability to play Grand Theft Auto 3 on the PlayStation Classic from beginning to end. I don't mind if the re3 project is dead, so long as it works. It's like I still use imgburn even though the project has been dead for over a decade. but if it can do what I wanted it to, do i really need updates? often times i feel people are just updating for the sake of updating

But yeah thanks for answering, i think I'll just stick with using re3 even though it's no longer updated. The other day I did a git clone of the latest librw and added it into the re3 vendor folder and it works.
