### ISSUE TITLE
[Bug?] Camera rotation using `sk::CameraTilt` and `sk::CameraPan` makes the camera also rotate on Z axis

### ISSUE THREAD

**Issue by Davilarek** [aap/librw#130]
Camera rotation using `sk::CameraTilt` and `sk::CameraPan` makes the camera also rotate on Z axis...
The issue also appears in the built-in `tools/camera` example.
Using these lines:
```c++
sk::CameraTilt(camera, nil, deltaY);
sk::CameraPan(camera, nil, deltaX);
```
I'm not sure if it's a bug in the engine or issue with my code somehow.
Here's a video showing the issue.

https://github.com/aap/librw/assets/62715937/2c227285-3bcd-445d-992f-a47b4a1fba80

**Comment by aap** [comment]
Not entirely sure but I suspect it's correct. I don't really use that function, probably used it for porting some RW example. I have better camera things in my own programs, this for instance: https://github.com/aap/librw/blob/master/tools/playground/camera.cpp
