### ISSUE TITLE
Which version of RW?

### ISSUE THREAD

**Issue by BJNFNE** [aap/librw#131]
Which version is this trying to reimplement of RenderWare Engine? btw nice work!
btw does you know how to identify from an game executable which version of RenderWare were used in the Game?

**Comment by aap** [comment]
It tries to be compatible with most versions but things like <= 3.1 skeletons might not work so well. also there are quite a few things which aren't actually implemented.

To identify the RW version you can check if you find callers of `_rwStreamWriteVersionedChunkHeader` (called by a macro `RwStreamWriteChunkHeader`).

**Comment by BJNFNE** [comment]
i can not find them, are there other methods to identify the version?
i found something called like this string for an Game called Adiboo and the Energy Thieves: X:/sdk_3.6.0/rwaisdk/src/rwai/kyRWDataReader.cpp (could this be 3.6.0?)
And this for an Game called Adiboo and Paziral's Secret: //RenderWare/RW34Active/rwsdk/tool/anim/rtanim.c# (could this be then 3.4?)

**Comment by aap** [comment]
What would most likely be 3.6 and 3.4, yes

**Comment by BJNFNE** [comment]
Thank you
