### ISSUE TITLE
[Question] What is `TexCoords`? And how do I use it?

### ISSUE THREAD

**Issue by Davilarek** [aap/librw#133]
Hello there,
I'm stuck at trying to understand how UV maps work in librw's `Geometry`.
While looking at the source, I found `TexCoords` which I figured out it might be related to UV maps...
However, doing this:
```c++
    geometry->texCoords[0] = rwMallocT(rw::TexCoords, 1, 0);
    geometry->texCoords[0]->u = 2;
    geometry->texCoords[0]->v = 2;
```
Gives me undefined behavior where on each rerun gives me different results.
My goal is to set UV maps for a geometry.
Any examples or some assistance would be really useful. Thanks

**Comment by aap** [comment]
Why do you malloc this manually? Creating a geometry will allocate whatever you need. what are you tying to do? To set the tex coord of channel 0 for vertex i you do `geometry->texCoord[0][i].u = u; geometry->texCoord[0][i].v = v;`

**Comment by Davilarek** [comment]
Huh okay so that's how I use it. I guess that will work, thank you
> what are you tying to do?

I was trying to understand how UVs work in librw
