### ISSUE TITLE
Would it be possible/in-scope to implement the features used by RW after EA bought RW?

### ISSUE THREAD

**Issue by ChrisNonyminus** [aap/librw#134]
After reading about Renderware, I noticed that some time in 2004/2005, EA bought out RW, and it was used as an in-house render engine for games like The Sims 3, SC2013, and Spore, which all seem to use the same engine.
Would it be in scope to implement whatever new additions were made after this? SimCity 2013 has a debug build with full symbols, including those for renderware.
I am unsure however what differences there are between post-EA RW and pre-EA RW.

**Comment by aap** [comment]
I don't know these games. i doubt that anything from 2013 is even based on RW 3.x, but if you send me some symbols i can take a look what it is.

**Comment by ChrisNonyminus** [comment]
> I don't know these games. i doubt that anything from 2013 is even based on RW 3.x, but if you send me some symbols i can take a look what it is.

https://dg.getrektby.us/_files/Windows/[WIN]%20SimCity%202013%20(Dev%20Beta)%20(v253660365)%20[2013-01-14]%20(PDB).7z

**Comment by aap** [comment]
Just as i thought this is not RW3, so it's not related to my project here at all.

**Comment by ChrisNonyminus** [comment]
Ah, damn.
