### ISSUE TITLE
This repository does not have a code of conduct

### ISSUE THREAD

**Issue by ntauthority** [aap/librw#14]
Hi,

I just noticed your repository does not have a Code of Conduct applied to it. May I suggest you add one? I want to feel good about using this project, and have it be a safe space for many kittens.

Here's a good suggestion:

[link here]

Meow!

**Comment by quiret** [comment]
1. Add conduct
2. Wait for contributions
3. ???
4. PROFIT

Nice meeem, meow.

**Comment by aap** [comment]
Whatever, sissies...
