### ISSUE TITLE
Splitting files into src and include folders

### ISSUE THREAD

**Issue by quiret** [aap/librw#18]
How about putting all header files into a distinguished /include/librw/ folder so that you can put
#include <librw/collision.h>
into the source code? I think I have seen this directory pattern at other professional projects before. :)

**Comment by aap** [comment]
Hm, not so sure. I'm not a fan of hundreds of little include files. That's why I have rw.h which includes everything. RW generates the public headers by combining the smaller private headers. What do you have in mind?

**Comment by quiret** [comment]
I remember this weird collision.h issue and such a measure would be a precaution against it occuring again ;) On another note, might be more important for 'librwgta' because it collides with IIItest.

Seems alright. "rw.h" is a very good solution to the possible collision.
