### ISSUE TITLE
Can't use makefiles

### ISSUE THREAD

**Issue by RandomAnimeGamer** [aap/librw#21]
When I compiled the application, I opened the Developer Command Prompt for VS2015 and changed directories to the build folder. From there, I entered the command "nmake -f Makefile" only to get an error.
`Makefile(4) : fatal error U1034: syntax error : separator missing
Stop.`

Am I doing something wrong?

**Comment by aap** [comment]
I have not tried to compile it with VS makefiles, sorry.
