### ISSUE TITLE
GLAD support

### ISSUE THREAD

**Issue by AGraber** [aap/librw#33]
Support GLAD as an alternative OpenGL loader to use for platforms where GLEW isn't available (eg. Switch).

Let the system provide its own glad path as well for platform specific stuff when building

**Comment by ShFil119** [comment]
There's no sdl for switch?

**Comment by AGraber** [comment]
Switch does support SDL, but SDL is irrelevant. GLAD and GLEW are both OpenGL function loaders.

GLAD might not be necessary though since I'm now looking into porting GLEW into the switch (aarch64 + must use egl for loading). I'll close this issue if that's the case.

**Comment by fjtrujy** [comment]
Good idea, you can start adapting this library to work with the PS2.
