### ISSUE TITLE
Compilation fails in “../src/charset.cpp:35:8”

### ISSUE THREAD

**Issue by ghost** [aap/librw#34]
After type “make all” I get this error:  
``charset.cpp
../src/charset.cpp:35:8: error: ‘RWDEVICE’ does not name a type
   35 | static RWDEVICE::Im2DVertex *vertices;
      |        ^~~~~~~~``

If this can help, here is the “[log](https://cdn.discordapp.com/attachments/575874211936206879/753111208684683274/librw-log.txt)”.

**Comment by robante15** [comment]
How you resolve this problem?
