### ISSUE TITLE
`modulateEnvMap` doesn't exist

### ISSUE THREAD

**Issue by alextwothousand** [aap/librw#72]
When attempting to build reVC, I get an error telling me `modulateEnvMap` doesn't exist.
When I implemented it into librw's source, it compiled fine.

**Comment by aap** [comment]
I updated librw after the DMCA on reGTA and broke compatibility there. The version from feb 19th should be compatible.

**Comment by alextwothousand** [comment]
Is it OK if I make a PR with the changes I made? I'd much rather use the *newest* version of librw!

**Comment by aap** [comment]
no

**Comment by alextwothousand** [comment]
No? Why so?
What about in a separate branch, or in my own fork?

**Comment by aap** [comment]
Because i don't want old code in the current version. Hopefully reGTA will be back eventually.

**Comment by alextwothousand** [comment]
Understood. I will use my own fork in the time being.

**Comment by madebr** [comment]
Can this issue be closed?

**Comment by eugeneRover** [comment]
Thatnks for your job!

> I updated librw after the DMCA on reGTA and broke compatibility there. The version from feb 19th should be compatible.

Would you please tag (or even branch) that version ? It would be way easier for people to find it
